/** Demo / fallback data for pages not yet wired to the API. */

export const targetJobs = [
  {
    id: 1,
    title: "Data Analyst",
    icon: "📊",
    demand: "High",
    salary: "€38k–52k",
    skills: 12,
  },
  {
    id: 2,
    title: "Data Scientist",
    icon: "🧠",
    demand: "High",
    salary: "€45k–65k",
    skills: 18,
  },
  {
    id: 3,
    title: "Backend Developer",
    icon: "⚙️",
    demand: "Medium",
    salary: "€40k–58k",
    skills: 14,
  },
  {
    id: 4,
    title: "ML Engineer",
    icon: "🤖",
    demand: "High",
    salary: "€48k–70k",
    skills: 16,
  },
  {
    id: 5,
    title: "DevOps Engineer",
    icon: "☁️",
    demand: "Medium",
    salary: "€42k–60k",
    skills: 11,
  },
  {
    id: 6,
    title: "Fullstack Developer",
    icon: "💻",
    demand: "High",
    salary: "€40k–55k",
    skills: 15,
  },
];

export const internships = [
  {
    id: 1,
    logo: "🏢",
    company: "Acme Analytics",
    location: "Paris, France",
    match: 87,
    position: "Data Analyst Intern",
    type: "6 months • Hybrid",
    skills: ["Python", "SQL", "Power BI"],
  },
  {
    id: 2,
    logo: "🚀",
    company: "TechFlow",
    location: "Lyon, France",
    match: 74,
    position: "Junior Data Engineer",
    type: "4 months • Remote",
    skills: ["Python", "ETL", "AWS"],
  },
  {
    id: 3,
    logo: "📈",
    company: "Insight Labs",
    location: "Remote",
    match: 91,
    position: "ML Research Intern",
    type: "3 months • Remote",
    skills: ["Python", "scikit-learn", "Statistics"],
  },
  {
    id: 4,
    logo: "🌐",
    company: "CloudNine",
    location: "Marseille, France",
    match: 68,
    position: "DevOps Intern",
    type: "5 months • On-site",
    skills: ["Docker", "CI/CD", "Linux"],
  },
  {
    id: 5,
    logo: "💡",
    company: "DataBridge",
    location: "Toulouse, France",
    match: 82,
    position: "Business Intelligence Intern",
    type: "6 months • Hybrid",
    skills: ["SQL", "Tableau", "Excel"],
  },
  {
    id: 6,
    logo: "🔬",
    company: "BioStat Co",
    location: "Nantes, France",
    match: 76,
    position: "Data Science Intern",
    type: "4 months • Hybrid",
    skills: ["R", "Python", "Statistics"],
  },
];

export const extractedSkills = [
  { name: "Python", category: "Programming", level: 78 },
  { name: "SQL", category: "Data", level: 85 },
  { name: "Machine Learning", category: "AI/ML", level: 62 },
  { name: "Data Visualization", category: "Analytics", level: 70 },
  { name: "Statistics", category: "Math", level: 55 },
  { name: "Git", category: "Tools", level: 80 },
  { name: "FastAPI", category: "Backend", level: 45 },
  { name: "Communication", category: "Soft skills", level: 72 },
];
